# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QSPNetworkingDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QSPNetworkingDemo
    pod 'AFNetworking', '~>3.2.0'
    pod 'MBProgressHUD', '~> 1.1.0'

  target 'QSPNetworkingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QSPNetworkingDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
